name: repo-sync

on:
  workflow_dispatch:

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: elastic:kibana
        source_branch: main
        destination_branch: intermediate-branch
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: intermediate-branch
        destination_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
